version: '3'

volumes:
  database2: {}

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'budget'
      MYSQL_USER: 'budget'
      MYSQL_PASSWORD: 'test'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "33061:3306"
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
